version: '3'
services:
  app:
    build: app/
    tty: true
    stdin_open: true
    volumes:
      - dataset_volume:/dataset
      - ./code:/code
  dataset:
    build: data/
    volumes:
      - dataset_volume:/dataset
volumes:
  dataset_volume:
